---
site_name: Free Quran Distribution
default_translation: english
order_limit_per_day: 100
email_notifications: true
auto_refresh_interval: 60
max_daily_orders: 1000
debug_mode: false
maintenance_mode: false
low_stock_threshold: 50
auto_reorder_point: 50
