--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
email_on_new_order: true
email_daily_summary: true
email_weekly_report: true
sms_alerts_low_stock: true
webhook_url: false
notification_emails: false
