---
email_on_new_order: true
email_daily_summary: false
email_weekly_report: false
sms_alerts_low_stock: true
slack_notifications: false
webhook_url: https://discord.com/api/webhooks/1429519144675704905/vcbwrmh86w3nN2w3GrQV2sUcjC5lBk41TDGajZKrlShQBEmESYLcXKu274oZhtvVysnJ
notification_emails: ranazaheerahmed65@gmail.com
discord_webhook_url: https://discord.com/api/webhooks/1429519144675704905/vcbwrmh86w3nN2w3GrQV2sUcjC5lBk41TDGajZKrlShQBEmESYLcXKu274oZhtvVysnJ
whatsapp_webhook_url: false
enable_discord_notifications: true
enable_whatsapp_notifications: false
